### ISSUE TITLE
Firefox does not like <datalist> with values

### ISSUE THREAD

**Issue by Golmote** [PaulKinlan/iwanttouse.com#4]
Firefox (tested on version 38) does not seem to support `<datalist>` properly when the `<option>`s have both a content and a `value` attribute.

**Comment by PaulKinlan** [comment]
Interesting. I'll check it out.

**Comment by Golmote** [comment]
It provides autocompletion when entering a number, but does not display the "value".
![capture d ecran 2015-03-03 a 11 20 00](https://cloud.githubusercontent.com/assets/565460/6460405/4d7401b2-c197-11e4-8425-058985894c3f.png)

It does not provide autocompletion when entering a value.
![capture d ecran 2015-03-03 a 11 20 14](https://cloud.githubusercontent.com/assets/565460/6460406/4d991bd2-c197-11e4-82d8-7d459980fd73.png)

**Comment by PaulKinlan** [comment]
Seems to all work now
